default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge
  - post-rewrite
  - commit-msg
default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: name-tests-test
        args: [--pytest-test-first]
        exclude: ^tests/fixtures/.*\.py$
      - id: no-commit-to-branch
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys, --indent, '2']
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.16.0
    hooks:
      - id: pretty-format-toml
        args: [--no-sort, --indent, '4']
        exclude: ^uv\.lock$
      - id: pretty-format-yaml
        args: [--autofix, --indent, '2', --offset, '2', --preserve-quotes]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.7
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.36
    hooks:
      - id: pymarkdown

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']

  - repo: https://github.com/maxwinterstein/shfmt-py
    rev: v3.12.0.1
    hooks:
      - id: shfmt
        args: [-w, --indent=4, --case-indent, --binary-next-line]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/Mateusz-Grzelinski/actionlint-py
    rev: v1.7.11.24
    hooks:
      - id: actionlint
        additional_dependencies: [pyflakes>=3.0.1, shellcheck-py>=0.9.0.5]

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [--verbose]

  - repo: local
    hooks:
      - id: uv-sync
        name: uv-sync
        description: Automatically run `uv sync` on your repository after a checkout, pull or rebase
        entry: uv sync
        args: [--no-active, --locked]
        language: system
        always_run: true
        pass_filenames: false
        stages: [post-checkout, post-merge, post-rewrite]
